[package]
name = "uclanr"
about = "A cli app which generates random words"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = {version="4.3.12", features = ["derive"]}
